idcops/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url, include, static
from idcops import views
from idcops.list import ListModelView, ConfigUserListView
from idcops.detail import DetailModelView
from idcops.edit import NewModelView, EditModelView

app_name = 'idcops'


accounts_urls = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^profile/', views.ProfileView.as_view(), name='profile'),
    url(r'^password_change/$', views.password_change, name='password_change'),
    url(r'^password_change/done/$', views.password_change_done,
        name='password_change_done'),
    url(r'^password_reset/$', views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', views.password_reset_done,
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.reset, name='password_reset_confirm'),
    url(r'^reset/done/$', views.reset_done, name='password_reset_complete'),
]


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^welcome/', views.welcome, name='welcome'),
    url(r'^switch_onidc/', views.switch_onidc, name='switch_onidc'),
    url(r'^list/zonemap/', views.ZonemapView.as_view(), name='zonemap'),
    url(r'^(?:new/(?P<model>\w+))/$', NewModelView.as_view(), name='new'),
    url(r'^(?:list/(?P<model>\w+))/$', ListModelView.as_view(), name='list'),
    url(r'^(?:config/(?P<model>\w+))/$',
        ConfigUserListView.as_view(), name='config'),
    url(r'^(?:config/list/(?P<model>\w+))/$',
        ConfigUserListView.as_view(), name='config_list'),
    url(r'^(?:detail/(?:(?P<model>\w+)-(?P<pk>\d+)))/$',
        DetailModelView.as_view(), name='detail'),
    url(r'^(?:update/(?:(?P<model>\w+)-(?P<pk>\d+)))/$',
        EditModelView.as_view(), name='update'),
    url(r'^upload/$',
        views.SummernoteUploadAttachment.as_view(), name='upload'),
    url(r'^import/(?P<model>\w+)/$',
        views.ImportExcelView.as_view(), name='import'),
]


if settings.DEBUG:
    urlpatterns += static.static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static.static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

idcops/templates/accounts/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}数据中心运维平台 - IDCOPS{% endblock %}</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  {% load staticfiles %}
  <link rel="icon" href="{%static 'idcops/favicon.png'%}" sizes="32x32">
  <link rel="icon" href="{%static 'idcops/favicon.png'%}" sizes="192x192">
  <link rel="apple-touch-icon-precomposed" href="{%static 'idcops/favicon.png'%}">
  <meta name="msapplication-TileImage" content="{%static 'idcops/favicon.png'%}">
  <link rel="stylesheet" href="{% static 'idcops/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'idcops/css/AdminLTE.min.css' %}">
  <link rel="stylesheet" href="{% static 'idcops/css/font-awesome.min.css' %}">
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
{% block body %}
{% endblock %}
</html>

idcops/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load i18n admin_static %}
{% block title %}登录 数据中心运维平台 - IDCOPS{% endblock %}
{% block body %}
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="{% url 'idcops:index' %}"><b>idcops</b></a>
  </div>
    {% if messages %}
        {% for message in messages %}
        <div id="message" class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible no-margin">
          {{ message }}
        </div>
        {% endfor %}
    {% endif %}
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">登入系统</p>
{% if form.errors and not form.non_field_errors %}
<p class="error">
{% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
</p>
{% endif %}
{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="error">
    {{ error }}
</p>
{% endfor %}
{% endif %}
    <form action="{% url 'idcops:login' %}" method="post">{% csrf_token %} 
      <div class="form-group has-feedback">
        <input type="text" id="id_username" name="username" class="form-control" autocomplete="off" autofocus="autofocus" placeholder="工号">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="text"  onfocus="this.type='password'" id="id_password" name="password" class="form-control" autocomplete="off" placeholder="登录密码">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <input type="hidden" name="next" value="{{ next }}" />
        <!-- /.col -->
    <div class="row">
    <div class="col-xs-8"></div>
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
        </div>
        <!-- /.col -->
      </div>
    </form>
    <a href="{% url 'idcops:password_reset' %}">{% trans 'Forgotten your password or username?' %}</a>
  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->
</body>
{% endblock %}
</html>

idcops/templates/accounts/logout.html
{% extends "accounts/login.html" %}
{% load i18n admin_static static %}
{% block title %}退出登录{% endblock %}

{% block body %}
<body class="hold-transition lockscreen">
<!-- Automatic element centering -->
<div class="lockscreen-wrapper">
  <div class="lockscreen-logo">
    <b>idcops</b>
  </div>
  <!-- User name -->
  <div class="lockscreen-name">idcops</div>
  <!-- START LOCK SCREEN ITEM -->
  <div class="lockscreen-item">
    <!-- lockscreen image -->
    <div class="lockscreen-image">
      <img src="{% static 'idcops/img/default.png' %}" alt="User Image">
    </div>
    <form class="lockscreen-credentials" action="" method="post">
      <div class="input-group">
        <input type="text" class="form-control" disabled="disabled" autocomplete="off"  placeholder="{%now 'Ymd'%}">

      </div>
    </form>
  </div>
  <div class="text-center">
    <a href="{% url 'idcops:login' %}">{% trans 'Log in again' %}</a>
  </div>
  <div class="lockscreen-footer text-center">
    <p>{% trans "Thanks for spending some quality time with the Web site today." %}</p><br>
    Copyright &copy; 2016 <b>idcops</b><br>
    All rights reserved
  </div>
</div>
<!-- /.center -->
</body>
{% endblock %}

idcops/templates/accounts/password_change_done.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% block userlinks %}{% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}<a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %}{% trans 'Change password' %} / <a href="{% url 'idcops:logout' %}">{% trans 'Log out' %}</a>{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'idcops:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password change' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
<p>{% trans 'Your password was changed.' %}</p>
{% endblock %}

<div class="login-box">
  <div class="login-logo">
    <a href="{% url 'idcops:index' %}">{% trans 'Home' %}</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">

    {% if messages %}
        {% for message in messages %}
        <div id="message" class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible no-margin">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
          {{ message }}
        </div>
        {% endfor %}
    {% endif %}

    <p class="login-box-msg">Login ...</p>

{% if form.errors and not form.non_field_errors %}
<p class="error">
{% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="error">
    {{ error }}
</p>
{% endfor %}
{% endif %}

    <form action="" method="post">{% csrf_token %}
      <div class="form-group has-feedback">
        <input type="text" id="id_username" name="username" class="form-control" autocomplete="off" autofocus="autofocus" placeholder="工号">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="text"  onfocus="this.type='password'" id="id_password" name="password" class="form-control" autocomplete="off" placeholder="登录密码">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
        <!-- /.col -->
    <div class="row">
    <div class="col-xs-8"></div>
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
        </div>
        <input type="hidden" name="next" value="{{ next }}" />
        <!-- /.col -->
      </div>
    </form>
    <a href="{% url 'idcops:password_reset' %}">{% trans 'Forgotten your password or username?' %}</a>
  </div>
  <!-- /.login-box-body -->
</div>

idcops/templates/accounts/password_change_form.html
{% extends 'base/edit.html' %}
{% load i18n static app_extras%}
{% block title %}修改密码 数据中心运维平台 - IDCOPS{% endblock %}
{% block content-header %}<h1>修改密码 <small> {{request.user}}</small></h1>{% endblock %}

{% block form %}
<form method="post" class="form-horizontal">{% csrf_token %}
<div class="box-body">
{% if form.errors %}
    <p class="errornote">
    {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
{% endif %}


<p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

<fieldset class="module aligned wide margin-bottom">

<div class="form-row">
    {{ form.old_password.errors }}
    {{ form.old_password.label_tag }} {{ form.old_password|addcss:"form-control" }}
</div>

<div class="form-row">
    {{ form.new_password1.errors }}
    {{ form.new_password1.label_tag }} {{ form.new_password1|addcss:"form-control" }}
    {% if form.new_password1.help_text %}
    <div class="help">{{ form.new_password1.help_text|safe }}</div>
    {% endif %}
</div>

<div class="form-row">
{{ form.new_password2.errors }}
    {{ form.new_password2.label_tag }} {{ form.new_password2|addcss:"form-control" }}
    {% if form.new_password2.help_text %}
    <div class="help">{{ form.new_password2.help_text|safe }}</div>
    {% endif %}
</div>

</fieldset>

<div class="submit-row">
    <input type="submit" value="{% trans 'Change my password' %}" class="btn btn-primary btn-sm" />
</div>

</div>
</form>
{%endblock form%}

idcops/templates/accounts/password_reset_complete.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'idcops:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}

{% block content %}

<p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a href="{% url 'idcops:login' %}">{% trans 'Log in' %}</a></p>

{% endblock %}

idcops/templates/accounts/password_reset_confirm.html
{% extends 'accounts/base.html' %}
{% load i18n admin_static static %}
{% block title %}{{ title }} 数据中心运维平台{% endblock %}

{% block body %}
<body class="hold-transition login-page">
  <div class="login-box">
    <div class="login-logo">
      <a href="{% url 'idcops:index' %}"><b>IDC 运维管理平台</b></a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
      <p class="login-box-msg">{% trans 'Password reset confirmation' %}</p>

      {% if validlink %}

      <p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>
      
      <form method="post">{% csrf_token %}

        <div class="form-group has-feedback">
            {{ form.new_password1.errors }}
            <label for="id_new_password1">{% trans 'New password:' %}</label>
            <input type="password" name="new_password1" required="" id="id_new_password1" class="form-control" autocomplete="off" autofocus="autofocus">
        </div>
        <div class="form-group has-feedback">
            {{ form.new_password2.errors }}
            <label for="id_new_password2">{% trans 'Confirm password:' %}</label>
            <input type="password" name="new_password2" required="" id="id_new_password2" class="form-control" autocomplete="off" autofocus="autofocus">
        </div>
        <div class="row">
            <div class="col-xs-8"></div>
            <div class="col-xs-4">
              <button type="submit" class="btn btn-primary btn-block btn-flat" value="{% trans 'Change my password' %}"> 确定</button>
            </div>
            <!-- /.col -->
          </div>
      </form>
      
      {% else %}
      
      <p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>
      
      {% endif %}
    </div>
    <!-- /.login-box-body -->
  </div>
  <!-- /.login-box -->
</body>
{% endblock %}

idcops/templates/accounts/password_reset_done.html
{% extends "accounts/login.html" %}
{% load i18n admin_static %}
{% block title %}{% trans 'Password reset' %}{% endblock %}

{% block body %}

<body class="hold-transition lockscreen">
    <!-- Automatic element centering -->
    <div class="lockscreen-wrapper">
        <div class="lockscreen-logo">
            <b>IDC 运维管理平台</b>
        </div>
        <!-- User name -->
        <div class="lockscreen-name">idcops</div>
        <!-- START LOCK SCREEN ITEM -->
        <br>
        <div class="reset-message">
            <p>{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}
            </p>

            <p>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}
            </p>

        </div>
        <div class="text-center">
            <a href="{% url 'idcops:login' %}">{% trans 'Log in again' %}</a>
        </div>
        <div class="lockscreen-footer text-center">

            <br>
            Copyright &copy; 2016 <b>IDCOPS</b><br>
            All rights reserved
        </div>
    </div>
    <!-- /.center -->
</body>
{% endblock %}

idcops/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'idcops:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

idcops/templates/accounts/password_reset_form.html
{% extends 'accounts/base.html' %}
{% load i18n static %}
{% block body %}
<body class="hold-transition lockscreen">
<!-- Automatic element centering -->
<div class="lockscreen-wrapper">
  <div class="lockscreen-logo">
    <b>idcops</b>
  </div>
  <p>{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>
  <!-- User name -->
  <div class="lockscreen-name">{{request.user}}</div>
  <!-- START LOCK SCREEN ITEM -->
  <div class="lockscreen-item">
    <!-- lockscreen image -->
    <div class="lockscreen-image">
      <img src="{% static 'idcops/img/default.png' %}" alt="User Image">
    </div>
    <form class="lockscreen-credentials" method="post">{% csrf_token %}
        <div class="input-group">
            {{ form.email.errors }}
            <input type="email" class="form-control" autocomplete="off" name="email" maxlength="254" required="" placeholder="{% trans 'Email address' %}" id="id_email">
            <div class="input-group-btn">
              <button type="button" class="btn"><i class="fa fa-arrow-right text-muted"></i></button>
            </div>
        </div>
        <!--input type="submit" value="{% trans 'Reset my password' %}" /-->
    </form>
  </div>
  <div class="text-center">
    <a href="{% url 'idcops:login' %}">{% trans 'Log in again' %}</a>
  </div>
  <div class="lockscreen-footer text-center">
    Copyright &copy; 2016 <b>idcops</b><br>
    All rights reserved
  </div>
</div>
<!-- /.center -->
</body>

{% endblock %}

idcops/templates/accounts/profile.html
{% extends 'base/base.html' %}
{% block title %}个人设置 数据中心运维平台 - IDCOPS{% endblock %}
{% block content-header %}<h1>用户中心 <small> 个人设置</small></h1>{% endblock %}
{% block breadcrumb %}
<li><a href="{% url 'idcops:index' %}"><i class="fa fa-dashboard"></i>
  {% if meta %}{{meta.logo}}{% else %}仪表盘{% endif %}
</a></li>
<li class="active"><i class="{{meta.icon}}"></i> 个人设置</li>
{% endblock %}