idcops/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url, include, static
from idcops import views
from idcops.list import ListModelView, ConfigUserListView
from idcops.detail import DetailModelView
from idcops.edit import NewModelView, EditModelView

app_name = 'idcops'


accounts_urls = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^profile/', views.ProfileView.as_view(), name='profile'),
    url(r'^password_change/$', views.password_change, name='password_change'),
    url(r'^password_change/done/$', views.password_change_done,
        name='password_change_done'),
    url(r'^password_reset/$', views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', views.password_reset_done,
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.reset, name='password_reset_confirm'),
    url(r'^reset/done/$', views.reset_done, name='password_reset_complete'),
]


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^welcome/', views.welcome, name='welcome'),
    url(r'^switch_onidc/', views.switch_onidc, name='switch_onidc'),
    url(r'^list/zonemap/', views.ZonemapView.as_view(), name='zonemap'),
    url(r'^(?:new/(?P<model>\w+))/$', NewModelView.as_view(), name='new'),
    url(r'^(?:list/(?P<model>\w+))/$', ListModelView.as_view(), name='list'),
    url(r'^(?:config/(?P<model>\w+))/$',
        ConfigUserListView.as_view(), name='config'),
    url(r'^(?:config/list/(?P<model>\w+))/$',
        ConfigUserListView.as_view(), name='config_list'),
    url(r'^(?:detail/(?:(?P<model>\w+)-(?P<pk>\d+)))/$',
        DetailModelView.as_view(), name='detail'),
    url(r'^(?:update/(?:(?P<model>\w+)-(?P<pk>\d+)))/$',
        EditModelView.as_view(), name='update'),
    url(r'^upload/$',
        views.SummernoteUploadAttachment.as_view(), name='upload'),
    url(r'^import/(?P<model>\w+)/$',
        views.ImportExcelView.as_view(), name='import'),
]


if settings.DEBUG:
    urlpatterns += static.static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static.static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

idcops/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import uuid
import json
import socket
import struct
import ipaddress

from django.db import models, transaction
from django.db.models.fields import BLANK_CHOICE_DASH
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.fields import (
    GenericForeignKey, GenericRelation
)

from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import formats, timezone
from django.utils.encoding import force_text
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _
from django.views.generic.base import logger
from django.urls import reverse_lazy

# Create your models here.

from idcops.lib.fields import NullableCharField, IPNetwork
from idcops.lib.models import NamedMixin


def upload_to(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    today = timezone.datetime.now().strftime(r'%Y/%m/%d')
    return os.path.join('uploads', today, filename)


EXT_NAMES = (
    'level', 'hidden', 'dashboard', 'metric', 'icon',
    'icon_color', 'default_filters', 'list_display', 'extra_fields'
)

models.options.DEFAULT_NAMES += EXT_NAMES

COLOR_MAPS = (
    ("red", "红色"),
    ("orange", "橙色"),
    ("yellow", "黄色"),
    ("green", "深绿色"),
    ("blue", "蓝色"),
    ("muted", "灰色"),
    ("black", "黑色"),
    ("aqua", "浅绿色"),
    ("gray", "浅灰色"),
    ("navy", "海军蓝"),
    ("teal", "水鸭色"),
    ("olive", "橄榄绿"),
    ("lime", "高亮绿"),
    ("fuchsia", "紫红色"),
    ("purple", "紫色"),
    ("maroon", "褐红色"),
    ("white", "白色"),
    ("light-blue", "暗蓝色"),
)


class Mark(models.Model):
    CHOICES = (
        ('shared', "已共享的"),
        ('pre_share', "预共享的"),
    )
    mark = models.CharField(
        max_length=64, choices=CHOICES,
        blank=True, null=True,
        verbose_name="系统标记", help_text="系统Slug内容标记")

    class Meta:
        level = 0
        hidden = False
        dashboard = False
        metric = ""
        icon = 'fa fa-circle-o'
        icon_color = ''
        default_filters = {'deleted': False}
        list_display = '__all__'
        extra_fields = []
        abstract = True

    @cached_property
    def get_absolute_url(self):
        opts = self._meta
        # if opts.proxy:
        #    opts = opts.concrete_model._meta
        url = reverse_lazy('idcops:detail', args=[opts.model_name, self.pk])
        return url

    @cached_property
    def get_edit_url(self):
        opts = self._meta
        url = reverse_lazy('idcops:update', args=[opts.model_name, self.pk])
        return url

    def title_description(self):
        return self.__str__()


class Creator(models.Model):
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT,
        related_name="%(app_label)s_%(class)s_creator",
        verbose_name="创建人", help_text="该对象的创建人")

    class Meta:
        abstract = True


class Operator(models.Model):
    operator = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT,
        related_name="%(app_label)s_%(class)s_operator",
        blank=True, null=True,
        verbose_name="修改人", help_text="该对象的修改人"
    )

    class Meta:
        abstract = True


class Created(models.Model):
    created = models.DateTimeField(
        default=timezone.datetime.now, editable=True,
        verbose_name="创建日期", help_text="该对象的创建日期"
    )

    class Meta:
        abstract = True


class Modified(models.Model):
    modified = models.DateTimeField(
        auto_now=True, verbose_name="修改日期",
        help_text="该对象的修改日期"
    )

    class Meta:
        abstract = True
        ordering = ['-modified']


class Actived(models.Model):
    actived = models.NullBooleanField(
        default=True, verbose_name="已启用",
        help_text="该对象是否为有效资源"
    )

    class Meta:
        abstract = True


class Deleted(models.Model):
    deleted = models.NullBooleanField(
        default=False,
        verbose_name="已删除", help_text="该对象是否已被删除"
    )

    class Meta:
        abstract = True


class Parent(models.Model):
    parent = models.ForeignKey(
        'self',
        blank=True, null=True, on_delete=models.SET_NULL,
        related_name="%(app_label)s_%(class)s_parent",
        verbose_name="父级对象", help_text="该对象的上一级关联对象"
    )

    class Meta:
        abstract = True


class Onidc(models.Model):
    onidc = models.ForeignKey(
        'Idc',
        blank=True, null=True, on_delete=models.PROTECT,
        related_name="%(app_label)s_%(class)s_onidc",
        verbose_name="所属机房", help_text="该资源所属的机房"
    )

    class Meta:
        abstract = True


class Tag(models.Model):
    tags = models.ManyToManyField(
        'Option',
        blank=True, limit_choices_to={'flag__icontains': 'tags'},
        related_name="%(app_label)s_%(class)s_tags",
        verbose_name="通用标签",
        help_text="可拥有多个标签,字段数据来自机房选项"
    )

    class Meta:
        abstract = True


class ClientAble(models.Model):
    client = models.ForeignKey(
        'Client',
        on_delete=models.PROTECT,
        null=True, blank=True,
        related_name="%(app_label)s_%(class)s_client",
        verbose_name="所属客户",
        help_text="该资源所属的客户信息"
    )

    class Meta:
        abstract = True


class RackAble(models.Model):
    rack = models.ForeignKey(
        'Rack',
        on_delete=models.CASCADE,
        null=True, blank=True,
        related_name="%(app_label)s_%(class)s_rack",
        verbose_name="所属机柜",
        help_text="该资源所属的机柜信息"
    )

    class Meta:
        abstract = True


class Intervaltime(models.Model):
    start_time = models.DateTimeField(
        default=timezone.datetime.now, editable=True,
        verbose_name="开始时间", help_text="该对象限定的开始时间"
    )
    end_time = models.DateTimeField(
        default=timezone.datetime.now, editable=True,
        null=True, blank=True,
        verbose_name="结束时间", help_text="该对象限定的结束时间"
    )

    class Meta:
        abstract = True


class PersonTime(Creator, Created, Operator, Modified):
    class Meta:
        abstract = True


class ActiveDelete(Actived, Deleted):
    class Meta:
        abstract = True


class Contentable(Onidc, Mark, PersonTime, ActiveDelete):
    content_type = models.ForeignKey(
        ContentType,
        models.SET_NULL,
        blank=True,
        null=True,
        verbose_name=_('content type'),
        related_name="%(app_label)s_%(class)s_content_type",
        limit_choices_to={'app_label': 'idcops'}
    )
    object_id = models.PositiveIntegerField(
        _('object id'), blank=True, null=True)
    object_repr = GenericForeignKey('content_type', 'object_id')
    content = models.TextField(verbose_name="详细内容", blank=True)

    def __str__(self):
        return force_text(self.object_repr)

    class Meta:
        abstract = True


class Comment(Contentable):
    class Meta(Mark.Meta):
        level = 2
        hidden = getattr(settings, 'HIDDEN_COMMENT_NAVBAR', True)
        default_permissions = ('view', 'add', 'change', 'delete', 'exports')
        verbose_name = verbose_name_plural = "备注信息"


class Configure(Contentable):
    class Meta(Mark.Meta):
        level = 2
        hidden = getattr(settings, 'HIDDEN_CONFIGURE_NAVBAR', True)
        default_permissions = ('view', 'add', 'change', 'delete', 'exports')
        verbose_name = verbose_name_plural = "用户配置"

    def __str__(self):
        return "{}-{} : {}".format(self.creator, self.content_type, self.pk)


class Remark(models.Model):
    comment = GenericRelation(
        'Comment',
        related_name="%(app_label)s_%(class)s_comment",
        verbose_name="备注信息")

    @property
    def remarks(self):
        return self.comment.filter(deleted=False, actived=True)

    class Meta:
        abstract = True


class Syslog(Contentable):
    action_flag = models.CharField(_('action flag'), max_length=32)
    message = models.TextField(_('change message'), blank=True)
    object_desc = models.CharField(
        max_length=128,
        verbose_name="对象描述"
    )
    related_client = models.CharField(
        max_length=128,
        blank=True, null=True,
        verbose_name="关系客户"
    )

    def title_description(self):
        time = formats.localize(timezone.template_localtime(self.created))
        text = '{} > {} > {}了 > {}'.format(
            time, self.creator, self.action_flag, self.content_type
        )
        return text

    class Meta(Mark.Meta):
        icon = 'fa fa-history'
        list_display = [
            'created', 'creator', 'action_flag', 'content_type',
            'object_desc', 'related_client', 'message', 'actived',
        ]
        default_permissions = ('view', 'add', 'change', 'delete', 'exports')
        ordering = ['-created', ]
        verbose_name = verbose_name_plural = _('log entries')


class User(AbstractUser, Onidc, Mark, ActiveDelete, Remark):
    slaveidc = models.ManyToManyField(
        'Idc',
        blank=True,
        verbose_name="附属机房",
        related_name="%(app_label)s_%(class)s_slaveidc"
    )
    upper = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        verbose_name="直属上级",
        related_name="%(app_label)s_%(class)s_upper"
    )
    mobile = models.CharField(max_length=16, blank=True, verbose_name="手机号码")
    avatar = models.ImageField(
        upload_to='avatar/%Y/%m/%d',
        default="avatar/default.png",
        verbose_name="头像"
    )
    settings = models.TextField(
        blank=True,
        verbose_name=_("settings"),
        help_text=_("user settings use json format")
    )

    def __str__(self):
        return self.first_name or self.username

    def title_description(self):
        text = '{} > {} '.format(
            self.onidc, self.__str__()
        )

idcops/templates/base/base_confirmation.html
{% extends 'base/base.html' %}
{% load i18n l10n admin_urls static %}
{% load app_extras static %}
{% block content-header %}
<h1>{{meta.verbose_name}} <small> {{object}}</small></h1>
{% endblock %}

{% block main-content %}
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">您确定要 {{action_name}} 选中的所有 {{meta.verbose_name}} ？</h3>
  </div>

  {%block form%}
  <form method="post">{% csrf_token %}
  <div class="box-body">
    
    {% for obj in queryset %}
    <p><a  data-toggle="modal" data-target="#modal-lg" href="{%url 'idcops:detail' meta.model_name obj.pk%}">{{obj}}</a></p>
    <input type="hidden" name="index" value="{{ obj.pk|unlocalize }}" />
    {% endfor %}
    <input type="hidden" name="action" value="{{action}}" />
    <input type="hidden" name="post" value="yes" />
    <input type="submit" class="btn btn-danger btn-sm margin-r-5" value="确定{{action_name}}" />
    <a href="{%url 'idcops:list' meta.model_name%}" class="btn btn-default btn-sm">
      <span>返回列表</span>
    </a>
  </div>
  </form>
  {%endblock form%}
  <div class="box-footer">

  </div>
</div>
{% endblock main-content %}

idcops/templates/base/config_list.html
{% extends 'base/base.html' %}
{% load static app_extras i18n %}
{% block title %}自定义{{meta.title}}列表字段{% endblock %}
{% block extra-css %}
{% endblock %}

{% block content-header %}<h1>{{meta.verbose_name}} <small> 自定义{{meta.verbose_name}}列表字段</small></h1>{% endblock %}

{% block breadcrumb %}
<li><a href="{% url 'idcops:index' %}"><i class="fa fa-dashboard"></i>
    {% if meta %}{{meta.logo}}{% else %}仪表盘{% endif %}
  </a></li>
<li><i class="{{meta.icon}}"></i> {{meta.verbose_name}}</li>
<li class="active hidden-xs">
  <a title="设置列表字段" href="{%url 'idcops:list' meta.model_name%}?config=true">
    <span> 配置列表</span>
  </a>
</li>
{% endblock %}


{% block main-content %}
<div class="box box-warning">
  <div class="box-header with-border">
    <h3 class="box-title"> 自定义{{meta.verbose_name}}列表字段</h3>
    <div class="box-tools pull-right">
      <div class="btn-group margin-r-5">
        <button type="button" class="btn btn-default btn-sm" onclick="window.history.go(-1)">
          <i class="fa fa-arrow-circle-o-left"></i><span> 返回上一页</span>
        </button>
      </div>
    </div>
  </div>
  {%block form%}
  <form action="" method="POST" id="{{meta.model_name}}-config_list">
    {% csrf_token %}
    <div class="box-body">
      <p>左右拖拽可定制列表的字段，上下拖拽可定制列表的顺序。<span class="text-red">右边绿色部分的元素是当前列表或配置后的列表字段。</span></p>
      <div class="form-group">
        <div class="list-header">
          <div class="row">
            <div id="unused_list_fields" class="list-groupd col-md-6">
              <label for="unused_fields" class="control-label">
                未在列表中展示的字段:
              </label>
              {% for field in fields_metadata.unused_list_fields%}
              <div class="list-field-item external-event bg-gray" name="{{field.name}}">
                <input type="hidden" disabled="disabled" checked="checked" value="{{field.name}}" name="list_display">
                {{field.verbose_name}}
              </div>
              {% endfor %}
            </div>

            <div id="current_list_display" class="list-groupd col-md-6">
              <label for="used_fields" class="control-label">
                当前列表中展示的字段和顺序:
              </label>
              {% for field in fields_metadata.current_list_display%}
              <div class="list-field-item external-event bg-green" name="{{field.name}}">
                <input type="hidden" checked="checked" value="{{field.name}}" name="list_display">
                {{field.verbose_name}}
              </div>
              {% endfor %}
            </div>

          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="list_only_date" class="control-label">请选择日期时间字段格式:</label>
        <div style="width: 100%;" class="btn-group" data-toggle="buttons">
          <label class="btn btn-primary btn-sm{%if fields_metadata.only_date == "0" %} active{%endif%}">
            <input type="radio" name="list_only_date" value="0" autocomplete="off" {%if fields_metadata.only_date == "0" %}checked{%endif%}> 显示日期和时间
          </label>
          <label class="btn btn-primary btn-sm{%if fields_metadata.only_date == "1" %} active{%endif%}">
            <input type="radio" name="list_only_date" value="1" autocomplete="off" {%if fields_metadata.only_date == "1" %}checked{%endif%}> 仅显示日期
          </label>
        </div>
        <p class="help-block">例如：2020-11-03 16:16:16（日期和时间）</p>
      </div>

    </div>
    <div class="box-footer">
      <button type="button" class="btn btn-default btn-sm margin-r-5" onclick="window.history.go(-1)">
        <span> 取消并返回</span>
      </button>
      <div class="btn-group pull-right">
        <button type="submit" name="_saverlist" class="btn btn-primary btn-sm">提交并返回列表</button>
      </div>
    </div>
  </form>
  {%endblock form%}
</div>
{% endblock main-content %}
{% block extra-js %}
<script src="{%static 'idcops/js/Sortable.js'%}"></script>
<script>
  var LeftEl = document.getElementById('unused_list_fields');
  var RightEl = document.getElementById('current_list_display')
  new Sortable(LeftEl, {
    group: 'shared',
    animation: 150,
    filter: '.control-label',
    onAdd: function (evt) {
      [].forEach.call(LeftEl.querySelectorAll('input[name="list_display"]'), function(item) {
        item.setAttribute('disabled', 'disabled')
      });
    }  
  });

  new Sortable(RightEl, {
    group: 'shared',
    animation: 150,
    filter: '.control-label',
    onAdd: function (evt) {
      [].forEach.call(RightEl.querySelectorAll('input[name="list_display"]'), function(item) {
        item.removeAttribute('disabled')
      });
    },
  });

</script>
{% endblock extra-js %}

idcops/templates/base/list.html
{% extends 'base/base.html' %}
{% load static app_extras i18n %}
{% block title %}列表 {{meta.title}}{% endblock %}
{% block extra-css %}
<style>
@media print {
  a[href]:after {
    content: none !important;
  }
  th {
    padding: 3px 4px !important;
  }
  td {
    padding: 2px 4px !important;
  }
  footer {
    padding: 10px 15px !important;
  }
}
.table>thead:first-child>tr:first-child>th>a {
  color: #333 !important;
}
.table>thead:first-child>tr:first-child>th>a:hover,
.table>thead:first-child>tr:first-child>th>a:active,
.table>thead:first-child>tr:first-child>th>a:focus {
  color: #111 !important;
}
</style>
{% endblock %}

{% block content-header %}
  <h1>{{meta.verbose_name}}
<small>
    {% block header-left %}
      {% if request.GET.search %}
        查询"<b class="text-red"> {{request.GET.search}} </b>",共<b class="text-red"> {{page_obj.paginator.count}} </b>条, 显示第<b class="text-red"> {{page_obj.start_index}} </b>条到<b class="text-red"> {{page_obj.end_index}} </b>条.
        {% else %}
        共<b> {{page_obj.paginator.count}} </b>条, 显示第<b> {{page_obj.start_index}} </b>到<b> {{page_obj.end_index}} </b>条.
      {% endif %}
    {% endblock %}
    <span> 选中 <b id="select_count">0</b> 条.</span>
    <a id="select_all"  title="{% trans "Click here to select the objects across all pages" %}" style="display: none;" class="hidden-xs" href="javascript:void(0)"> 选中所有的 {{page_obj.paginator.count}} 条</a>
      <a id="select_page" style="display: none;" href="javascript:void(0)" class="hidden-xs">
        <b class="text-red">已选中剩余条目,请谨慎操作.</b>
        清除选中所有的<b class="text-red"> {{page_obj.paginator.count}}</b> 条
      </a>
    </small>

  </h1>
{% endblock %}

{% block breadcrumb %}
<li><a href="{% url 'idcops:index' %}"><i class="fa fa-dashboard"></i>
  {% if meta %}{{meta.logo}}{% else %}仪表盘{% endif %}
</a></li>
<li><i class="{{meta.icon}}"></i> {{meta.verbose_name}}</li>
<li class="active hidden-xs">
  <a title="设置列表字段" href="{%url 'idcops:config_list' meta.model_name%}">
    <span> 配置列表</span>
  </a>
</li>
{% endblock %}

{% block main-content %}
<form id="action-form" action="" method="POST">{% csrf_token %}
  <div class="box">
    {% block box-header %}
    <div class="box-header with-border no-print clearfix">
      <div id="table-tools" class="pull-left">

        {%if can_create%}
        <a class="btn btn-default btn-sm margin-r-5" href="{%url 'idcops:new' meta.model_name %}">
          <i class="fa fa-plus"></i><span class="hidden-xs"> 新建</span>
        </a>
        {%endif%}

        <!--button type="submit" disabled="disabled" name="action" value="print" class="action-related disabled btn btn-default btn-sm margin-r-5">
          <i class="fa fa-print"></i><span class="hidden-xs"> 打印</span>
        </button-->

        {% block table-sub-tools %}
          {%if actions%}
          {% for a in actions%}
              <button type="submit" disabled="disabled" name="action" value="{{ a.1 }}" class="action-related disabled btn btn-default btn-sm margin-r-5">
                 <i class="{{a.2}}"></i><span class="hidden-xs"> {{ a.3 }}</span>
              </button>
          {%endfor%}
          {%endif%}
        {% endblock table-sub-tools %}

      </div>
      {% block search %}
      <div class="pull-right">
        <div id="search" class="input-group input-group-sm" style="min-width: 200px; max-width: 230px;">
          <input type="text" name="search" class="form-control pull-right" autofocus="autofocus" autocomplete="off" {%if request.GET.search%}value="{{ request.GET.search }}"{%endif%} placeholder="查询{{meta.verbose_name}}">
          <div class="input-group-btn">
            <button type="button" class="btn btn-default"><i class="fa fa-search"></i></button>
          </div>
        </div>
      </div>
      {% endblock search %}
    </div>
    {% endblock %}

    <div class="box-body table-responsive">
        <table id="objects-list" class="table table-bordered table-hover table-condensed text-nowrap">
          <thead>
            <tr>
            {%for item in thead%}
              <th scope="col" name="{{item.field}}" {{item.class_attrib}}>
                {%if item.sortable%}
                  {%if item.is_sorted%}
                  <a title="正反序切换" href="{{item.toggle_link}}">{{item.text}}
                    <i class="fa fa-sort-alpha-{{item.sorted_key}}"></i>
                  </a>
                  <span class="no-print hidden-xs pull-right">
                    <a title="移除本列排序" href="{{item.remove_link}}">
                    <i class="fa fa-remove text-danger"></i>
                    </a>
                  </span>
                  {%else%}
                  <a title="点击可排序" href="{{item.toggle_link}}">{{item.text}}</a>
                  {%endif%}
                {%else%}
                  {{item.text}}
                {%endif%}
              </th>
            {%endfor%}
            </tr>
          </thead>
          <tbody>
          {%block objects-list%}
            {%for obj in tbody%}
              <tr>{{obj}}</tr>
            {%endfor%}
          {%endblock%}
          </tbody>
        </table>
    </div>
    <div class="box-footer no-print clearfix" style="display: block;">
      {% block box-footer-right %}
        {% if is_paginated %}
          <ul class="pagination pagination-sm no-margin pull-right">
            {% if paginate %}
            <div class="btn-group dropup pull-left">
              <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                {{paginate}}
              </ul>
            </div>
            {% endif %}
            {% if page_obj.has_previous %}
              <li><a href="{%get_query_string page=1 %}">首页</a></li>
              <li><a href="{%get_query_string page=page_obj.previous_page_number %}">上一页</a></li>
            {% else %}
              <li class="previous disabled"><a>上一页</a></li>
            {% endif %}
              <li class="previous disabled">
              <span>{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</span>
              </li>
            {% if page_obj.has_next %}
              <li><a href="{%get_query_string page=page_obj.next_page_number%}">下一页</a></li>
              <li><a href="{%get_query_string page='last'%}">末页</a></li>
            {% else %}
              <li class="previous disabled"><a>下一页</a></li>
            {% endif %}
          </ul>
        {% endif %}
      {% endblock %}
    </div>
  </div>
</form>
{% endblock main-content %}
{% block extra-js %}
<script src="{%static 'idcops/js/jquery.shiftcheckbox.js'%}"></script>
<script src="{%static 'idcops/js/table-dragger.min.js'%}"></script>
<!--script src="{%static 'idcops/js/actions.js'%}"></script-->
<script>
$(document).ready(function (){

  $('[data-toggle="tooltip"]').tooltip();

  $('body').on('hidden.bs.modal', '.modal', function () {
      $(this).removeData('bs.modal');
  });

  var ItemCounts = {{object_list.count}};
  var ThCheckBox = $("table thead tr th input[type='checkbox']");
  var TdCheckBox = $("table tbody tr td input[type='checkbox']");
  var RelDom = $("#table-tools .action-related");
  TdCheckBox.shiftcheckbox();

  function updateColor() {
    TdCheckBox.filter(':checked').parent().parent().addClass('success');
    TdCheckBox.not(':checked').parent().parent().removeClass('success');
  }

  function updateRelated(){
  var checked = TdCheckBox.filter(':checked');
  if (checked.length>0) {
    RelDom.filter(':disabled').removeClass('disabled').attr('disabled', false);
  }else{
    RelDom.addClass('disabled').attr('disabled', true);
  }
  }

  updateSelect = function() {
    var checked = TdCheckBox.filter(':checked');
    $("#select_count").html(checked.length);
    if (checked.length < ItemCounts) {
      ThCheckBox.prop('checked', false).val('page');
      $("#select_all, #select_page").hide();
    } else {
      ThCheckBox.prop('checked', true);
      {%if is_paginated%}$("#select_all").show();{%endif%}
    }
    updateColor();
    updateRelated();
  }

  TdCheckBox.click(function (){
    updateSelect();
  });

  $("#select_all").click(function(){
    TdCheckBox.prop('checked', 'checked');
    updateSelect();
    var _count = {{page_obj.paginator.count}};
    $("#select_count").html(_count);
    ThCheckBox.val('all');
    $(this).hide();
    $("#select_page").show();
  });

  $("#action-toggle").click(function(){
    TdCheckBox.prop('checked', $(this).prop('checked'));
    updateSelect();
    {%if is_paginated%}
      if (ThCheckBox.is('input:checked')){
        $("#select_all").show();
      } else {
        $("#select_all").hide();
      }
    {%endif%}
  });

  $("#select_page").click(function(){
    updateSelect();
    ThCheckBox.val('page');
    $(this).hide();
    $("#select_all").show();
  })

  $("#search button").on('click', function(e) {
      var value = $("#search input").val();
      if (value) {
        document.location.href="?search="+value+"";
      }
  });

  $("#search input").on("keydown", function (e) {
      if (e.keyCode == 13) {
        var value = $("#search input").val();
        if (value) {
          document.location.href="?search="+value+"";
        }
      }
  });

});
</script>

{% endblock extra-js %}