idcops/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url, include, static
from idcops import views
from idcops.list import ListModelView, ConfigUserListView
from idcops.detail import DetailModelView
from idcops.edit import NewModelView, EditModelView

app_name = 'idcops'


accounts_urls = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^profile/', views.ProfileView.as_view(), name='profile'),
    url(r'^password_change/$', views.password_change, name='password_change'),
    url(r'^password_change/done/$', views.password_change_done,
        name='password_change_done'),
    url(r'^password_reset/$', views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', views.password_reset_done,
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.reset, name='password_reset_confirm'),
    url(r'^reset/done/$', views.reset_done, name='password_reset_complete'),
]


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^welcome/', views.welcome, name='welcome'),
    url(r'^switch_onidc/', views.switch_onidc, name='switch_onidc'),
    url(r'^list/zonemap/', views.ZonemapView.as_view(), name='zonemap'),
    url(r'^(?:new/(?P<model>\w+))/$', NewModelView.as_view(), name='new'),
    url(r'^(?:list/(?P<model>\w+))/$', ListModelView.as_view(), name='list'),
    url(r'^(?:config/(?P<model>\w+))/$',
        ConfigUserListView.as_view(), name='config'),
    url(r'^(?:config/list/(?P<model>\w+))/$',
        ConfigUserListView.as_view(), name='config_list'),
    url(r'^(?:detail/(?:(?P<model>\w+)-(?P<pk>\d+)))/$',
        DetailModelView.as_view(), name='detail'),
    url(r'^(?:update/(?:(?P<model>\w+)-(?P<pk>\d+)))/$',
        EditModelView.as_view(), name='update'),
    url(r'^upload/$',
        views.SummernoteUploadAttachment.as_view(), name='upload'),
    url(r'^import/(?P<model>\w+)/$',
        views.ImportExcelView.as_view(), name='import'),
]


if settings.DEBUG:
    urlpatterns += static.static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static.static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

idcops/templates/rack/detail.html
{% extends 'base/detail.html' %}
{% load app_extras %}
{%block box-tools-extra%}
{% if object.actived %}
<div class="btn-group margin-r-5">
  {%if 'idcops.add_online' in perms %}
  <a class="btn btn-default btn-sm" href="/new/online/?rack_id={{object.pk}}">
    <i class="fa fa-server"></i><span class="hidden-xs"> 新建设备</span>
  </a>
  {%endif%}

  {%if 'idcops.add_rextend' in perms%}
  <a class="btn btn-default btn-sm" href="{%url 'idcops:new' 'rextend'%}?rack_id={{object.pk}}" data-toggle="modal" data-target="#modal-lg-static">
    <i class="fa fa-battery-2"></i><span class="hidden-xs"> 更新电量</span>
  </a>
  {%endif%}
</div>
{% endif %}
{%endblock box-tools-extra%}
{% block page-extra %}
{% rack_overview object.id '' %}
{% endblock %}

idcops/templates/rack/distribution.html
{% extends 'base/base.html' %}
{% load i18n l10n admin_urls static %}
{% load app_extras static %}
{% block extra-css %}
<link href="{% static 'idcops/css/select2.min.css' %}" type="text/css" media="all" rel="stylesheet">
{% endblock extra-css %}

{% block content-header %}
<h1>{{meta.verbose_name}}
<small>
  <b class="text-red"> {{queryset.count}} </b>个机柜
</small>
</h1>
{% endblock %}
{% block main-content %}

{% block form %}
<form method="post" class="form">
  {% csrf_token %}
<div class="box box-warning">
  <div class="box-header with-border">
    <h3 class="box-title">请您确认{{action_name}}清单</h3>
    <div class="box-tools pull-right">
      <input type="hidden" name="action" value="{{action}}" />
      <input type="hidden" name="post" value="yes" />
      <input type="submit" class="btn btn-danger btn-sm margin-r-5" value="确定{{action_name}}" />
      <a href="{%url 'idcops:list' meta.model_name%}" class="btn btn-default btn-sm">
        <span>返回列表</span>
      </a>
    </div>
  </div>
  <div class="box-body table-responsive margin-bottom">
  <table id="item-list" class="table table-bordered table-condensed">
    <thead>
      <tr class="active">
        <th width="3%"> #</th>
        <th>机柜名称</th>
        <th>机柜别名</th>
        <th>所在区域</th>
        <th width="30%">分配客户</th>
        <th width="10%">合同电力(A)</th>
        <th width="13%">机柜状态</th>
        <th width="13%">机柜类型</th>
      </tr>
    </thead>
    <tbody>
      {% for obj in queryset %}
      <input type="hidden" name="index" value="{{ obj.pk|unlocalize }}" />
      <input type="hidden" name="items" value="{{obj.pk}}" />
      <tr class="{% cycle '' 'active' %}">
        <td style="vertical-align:middle;">{{forloop.counter}}.</td>
        <td style="vertical-align:middle;">
          <a data-toggle="modal" data-target="#modal-lg" href="{{obj.get_absolute_url}}">{{obj}}</a>
        </td>
        <td style="vertical-align:middle;">{{obj.cname}}</td>
        <td style="vertical-align:middle;">{{obj.zone}}</td>
        <td class="clearfix" style="vertical-align:middle;">
          <select name="client-{{obj.pk}}" required class="form-control">
            <option value="">请选择一个客户</option>
            {%for client in clients%}
            <option value="{{client.id}}">{{client}}</option>
            {%endfor%}
          </select>
        </td>

        <td style="vertical-align:middle;">
          <input id="cpower-{{obj.pk}}" required="required" class="form-control" type="number" name="cpower-{{obj.pk}}" value="10" />
        </td>

        <td class="clearfix" style="vertical-align:middle;">
          <select name="status-{{obj.pk}}" class="form-control">
            {%for s in status%}
            <option value="{{s.id}}"{%if s.master%}selected{%endif%}>{{s}}</option>
            {%endfor%}
          </select>
        </td>

        <td class="clearfix" style="vertical-align:middle;">
          <select name="style-{{obj.pk}}" class="form-control">
            {%for style in styles%}
            <option value="{{style.id}}"{%if style.master%}selected{%endif%}>{{style}}</option>
            {%endfor%}
          </select>
        </td>
      </tr>
      {%endfor%}
    </tbody>
  </table>
  </div>

  <div class="box-footer">
    <div class="box-tools pull-right">
      <b>合计：</b><span id="total">{{queryset.count}}</span> 个
    </div>
  </div>
</div>
</form>
{% endblock form %}
{% endblock main-content %}

{% block extra-js%}
<script type="text/javascript" src="{%static 'idcops/js/select2.min.js' %}"></script>
<script type="text/javascript" src="{%static 'idcops/js/i18n/zh-CN.js' %}"></script>
<script>
$(document).ready(function (){

// reset modal cache
$('body').on('hidden.bs.modal', '.modal', function () {
    $(this).removeData('bs.modal');
});

// Select2
var Select = $("select");
if (Select.length != 0) {
  $("select").select2({language: "zh-CN"});
}

});

</script>
{% endblock extra-js%}

idcops/templates/rack/import.html
{% extends 'base/detail.html' %}
{% load static %}
{% block title %}批量导入 {{meta.title}}{% endblock %}

{% block main-content %}
<div class="box box-primary">
    {%block box-header%}
    <div class="box-header with-border">
        <h3 class="box-title"> 批量导入{{meta.verbose_name}}</h3>
        <div class="box-tools pull-right">
            <div class="btn-group margin-r-5">
                <button type="button" class="btn btn-default btn-sm" onclick="window.history.go(-1)">
                    <i class="fa fa-arrow-circle-o-left"></i><span> 返回上一页</span>
                </button>
            </div>
        </div>
    </div>
    {%endblock box-header%}
    {%block form%}
    <form action="" method="POST" enctype="multipart/form-data" role="form" class="form-horizontal"
        id="{{meta.model_name}}-new">
        {%block box-body%}
        <div class="box-body">
            {% csrf_token %}
            <div class="col-md-6 col-md-offset-3">
                <div class="form-group">
                    <b>注意事项：</b>
                    <ol>1、由于没有采用后台队列的方式，限制每次最多导入500个机柜</ol>
                    <p><a href="{%static 'idcops/file/rack_import_template.xlsx'%}">下载导入模板</a></p>
                </div>
                <hr>

                {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">
                        {{ field.label }}
                    </label>
                    {{ field }}
                    <div class="help-block">
                        {%if field.field.required%}
                        <span class="text-red">必填</span>
                        {%else%}
                        <span class="text-muted">选填</span>
                        {%endif%}
                        {{ field.help_text|safe}}
                        <div class="text-red">{{ field.errors|safe }}</div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {%endblock box-body%}
        {%block box-footer%}
        <div class="box-footer">
            <button type="button" class="btn btn-default btn-sm" onclick="window.history.go(-1)">取消并返回</button>
            <div class="btn-group pull-right">
                <button type="submit" class="btn btn-primary btn-sm margin-r-5">提交</button>
            </div>
        </div>
        {%endblock box-footer%}
    </form>
    {%endblock form%}
</div>
{% endblock %}

{% block extra-js %}
<script>
    $(document).ready(function () { });
</script>
{% endblock %}

idcops/templates/rack/list.html
{% extends 'base/list.html' %}

{% block table-sub-tools %}
{%if can_create%}
<a class="btn btn-default btn-sm margin-r-5" href="{%url 'idcops:import' meta.model_name %}">
    <i class="fa fa-cloud-upload"></i><span class="hidden-xs"> 批量导入</span>
  </a>
{% endif%}
{%if actions%}
{% for a in actions%}
    <button type="submit" disabled="disabled" name="action" value="{{ a.1 }}" class="action-related disabled btn btn-default btn-sm margin-r-5">
       <i class="{{a.2}}"></i><span class="hidden-xs"> {{ a.3 }}</span>
    </button>
{%endfor%}
{%endif%}
{% endblock table-sub-tools %}

idcops/templates/rack/overview.html
<table id="rack-detail" style="margin:0; padding:0;" class="table table-bordered text-center nowarp table-condensed">
  <thead>
    <tr class="active">
        <th style="width:2%" class="bg-light-blue">U</th>
        <th style="width:16%" class="bg-light-blue">设备编号</th>
        <th style="width:2%" class="bg-light-blue">U</th>
        <th>PDU</th>
        <th>设备SN号</th>
        <th>IP地址</th>
        <th>设备型号</th>
        <th>客户名称</th>
        <th class="no-print">操作</th>
    </tr>
  </thead>
  <tbody>
      {% for u in units %}
      {% if not u.actived %}
        <tr name="hasdevice" {%if u in obj_units%}class="danger"{%else%}class="success"{%endif%}>
          {%with ucount=u.online.units.all%}
          <td style="vertical-align: middle;" class="no-padding bg-light-blue">{{u}}</td>
          {%if not u.repeat%}
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding">
            <a href="{%url 'idcops:detail' 'online' u.online.pk %}">{{u.online.name}}</a>
          </td>
          {%endif%}
          <td style="vertical-align: middle;" class="no-padding bg-light-blue">{{u}}</td>
          {% if not u.repeat %}
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding">
            {%if u.online.pdus%}
              {%for pdu in u.online.pdus.all %}
                <span>{{pdu}} </span>
              {%endfor%}
            {%else%}
              <span>未录入 </span>
            {%endif%}
          </td>
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding">
            {%if u.online.sn|first == '_' %}<span>无法查看</span>{%else%}<span>{{ u.online.sn|upper }}</span>{%endif%}
          </td>
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding">{{u.online.ipaddr}}</td>
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding">{{u.online.model}}</td>
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding">{{u.online.client}}</td>
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding no-print">
          <a href="{%url 'idcops:update' 'online' u.online.pk %}">修改</a>
          </td>
          {%endif%}
          {%endwith%}
        </tr>
      {% else %}
        <tr name="nonedevice">
          <td class="no-padding bg-light-blue">{{u}}</td>
          <td class="no-padding"></td>
          <td class="no-padding bg-light-blue">{{u}}</td>
          <td class="no-padding"></td>
          <td class="no-padding"></td>
          <td class="no-padding"></td>
          <td class="no-padding"></td>
          <td class="no-padding"></td>
          <td class="no-padding no-print"></td>
        </tr>
      {% endif %}
      {% endfor %}
      <tr>
        <td class="no-padding bg-light-blue">-1</td>
        <td class="no-padding bg-light-blue"></td>
        <td class="no-padding bg-light-blue">-1</td>
        <!-- <td class="no-padding"></td>
        <td class="no-padding"></td>
        <td class="no-padding"></td>
        <td class="no-padding"></td>
        <td class="no-padding"></td>
        <td class="no-padding no-print"></td> -->
      </tr>
  </tbody>
</table>